config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/manage', as: 'rails_admin'
  get 'landings/index'

  resources :courses

  resources :firms

  resources :students

  resources :additional_fees

  resources :standards

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/firm.rb
# == Schema Information
#
# Table name: firms
#
#  id                     :integer          not null, primary key
#  name                   :string(255)
#  financial_year         :string(255)
#  academic_year          :string(255)
#  service_tax_applicable :boolean
#  service_tax_rate       :decimal(, )
#  service_tax_number     :string(255)
#  line_1                 :string(255)
#  line_2                 :string(255)
#  city                   :string(255)
#  country                :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#

class Firm < ActiveRecord::Base
  has_many :courses
  has_many :admissions

  validates_presence_of :name, on: :create, message: "can't be blank"
  validates_presence_of :service_tax_applicable, on: :create, message: "can't be blank"
  validates_presence_of :line_1, on: :create, message: "can't be blank"
  validates_presence_of :city, on: :create, message: "can't be blank"
  validates_presence_of :country, on: :create, message: "can't be blank"

  rails_admin do
    field :name
    field :financial_year
    field :academic_year
    field :service_tax_applicable
    field :service_tax_rate
    field :service_tax_number
    field :line_1
    field :line_2
    field :city
    field :country
  end

  def to_s
    self.name.to_s
  end

end

app/controllers/firms_controller.rb
class FirmsController < ApplicationController
  before_action :set_firm, only: [:show, :edit, :update, :destroy]

  # GET /firms
  # GET /firms.json
  def index
    @firms = Firm.all
  end

  # GET /firms/1
  # GET /firms/1.json
  def show
  end

  # GET /firms/new
  def new
    @firm = Firm.new
  end

  # GET /firms/1/edit
  def edit
  end

  # POST /firms
  # POST /firms.json
  def create
    @firm = Firm.new(firm_params)

    respond_to do |format|
      if @firm.save
        format.html { redirect_to @firm, notice: 'Firm was successfully created.' }
        format.json { render :show, status: :created, location: @firm }
      else
        format.html { render :new }
        format.json { render json: @firm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /firms/1
  # PATCH/PUT /firms/1.json
  def update
    respond_to do |format|
      if @firm.update(firm_params)
        format.html { redirect_to @firm, notice: 'Firm was successfully updated.' }
        format.json { render :show, status: :ok, location: @firm }
      else
        format.html { render :edit }
        format.json { render json: @firm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /firms/1
  # DELETE /firms/1.json
  def destroy
    @firm.destroy
    respond_to do |format|
      format.html { redirect_to firms_url, notice: 'Firm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_firm
      @firm = Firm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def firm_params
      params.require(:firm).permit(:name, :financial_year, :academic_year, :service_tax_applicable, :service_tax_rate, :service_tax_number)
    end
end

app/views/firms/_form.html.erb
<%= form_for @firm, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :financial_year, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :financial_year, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :academic_year, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :academic_year, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :service_tax_applicable, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :service_tax_applicable, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :service_tax_rate, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :service_tax_rate, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :service_tax_number, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :service_tax_number, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  firms_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>
<%= simple_form_for @firm do |f| %>
  <div class="row">
    <%= errors_for @firm %>
    <div class="col-md-6">
    <%= f.input :name %>
    <%= f.input :financial_year %>
    <%= f.input :academic_year %>
    <%= f.input :service_tax_applicable , :as => :check_box%>
    <%= f.input :service_tax_rate %>
    <%= f.input :service_tax_number %>
    </div>
    <div class="col-md-6">
    <%= f.input :date_of_birth ,as: :date_picker, :label => 'Date Of Birth',
                  input_html: {data: {date_options: {defaultDate: '01/01/1997'}}}  %>
    <%= f.label :address %>
    <%= f.simple_fields_for :address do |ff| %>
     <%= render 'addresses/address_field', f: ff %>
    <% end %>
    <%= f.button :submit %>
    </div>
  </div>
<% end %>

app/views/firms/edit.html.erb
<%- model_class = Firm -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Firm %></h1>
</div>
<%= render :partial => 'form' %>

app/views/firms/index.html.erb
<%- model_class = Firm -%>
<div class="page-header">
  <h1><%=t '.title', :default => Firm %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:financial_year) %></th>
      <th><%= model_class.human_attribute_name(:academic_year) %></th>
      <th><%= model_class.human_attribute_name(:service_tax_applicable) %></th>
      <th><%= model_class.human_attribute_name(:service_tax_rate) %></th>
      <th><%= model_class.human_attribute_name(:service_tax_number) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @firms.each do |firm| %>
      <tr>
        <td><%= firm.id %></td>
        <td><%= firm.name %></td>
        <td><%= firm.financial_year %></td>
        <td><%= firm.academic_year %></td>
        <td><%= firm.service_tax_applicable %></td>
        <td><%= firm.service_tax_rate %></td>
        <td><%= firm.service_tax_number %></td>
        <td><%=l firm.created_at, format: :long %></td>
        <td>
          <%= link_to firm_path(firm), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to firm_path(firm), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_firm_path,
            :class => 'btn btn-primary' %>

app/views/firms/new.html.erb
<%- model_class = Firm -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Firm %></h1>
</div>
<%= render :partial => 'form' %>

app/views/firms/show.html.erb
<%- model_class = Firm -%>
<div class="page-header">
  <h1><%=t '.title', :default => Firm %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @firm.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:financial_year) %></dt>
      <dd><pre class="prettyprint"><%= @firm.financial_year %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:academic_year) %></dt>
      <dd><pre class="prettyprint"><%= @firm.academic_year %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:service_tax_applicable) %></dt>
      <dd><pre class="prettyprint"><%= @firm.service_tax_applicable %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:service_tax_rate) %></dt>
      <dd><pre class="prettyprint"><%= @firm.service_tax_rate %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:service_tax_number) %></dt>
      <dd><pre class="prettyprint"><%= @firm.service_tax_number %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              firms_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_firm_path(@firm), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              firm_path(@firm),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>