config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/manage', as: 'rails_admin'
  get 'landings/index'

  resources :courses

  resources :firms

  resources :students

  resources :additional_fees

  resources :standards

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/student.rb
# == Schema Information
#
# Table name: students
#
#  id            :integer          not null, primary key
#  name          :string(255)
#  roll_no       :string(255)
#  gender        :integer
#  school        :string(255)
#  phone_1       :string(255)
#  phone_2       :string(255)
#  date_of_birth :date
#  line_1        :string(255)
#  line_2        :string(255)
#  city          :string(255)
#  country       :string(255)
#  created_at    :datetime
#  updated_at    :datetime
#

class Student < ActiveRecord::Base
  extend Enumerize

  has_many :additional_fee_payments
  has_many :admissions

  validates_presence_of :name, on: :create, message: "can't be blank"
  validates_presence_of :line_1, on: :create, message: "can't be blank"
  validates_presence_of :city, on: :create, message: "can't be blank"
  validates_presence_of :country, on: :create, message: "can't be blank"

  enumerize :gender, in: {:male => 1, :female => 2}, default: :male

  rails_admin do
    field :name
    field :roll_no
    field :gender
    field :school
    field :phone_1
    field :phone_2
    field :date_of_birth
    field :line_1
    field :line_2
    field :city
    field :country
  end

  def to_s
    self.name.to_s
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  def index
    @students = Student.all
  end

  # GET /students/1
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /students/1
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /students/1
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :roll_no, :gender, :school, :phone_1, :phone_2, :date_of_birth, :line_1, :line_2, :city, :country)
    end
end

app/views/students/_form.html.erb
<%= simple_form_for @student do |f| %>
  <div class="row">
    <%= errors_for @student %>
    <div class="col-md-6">
    <%= f.input :name %>
    <%= f.input :roll_no %>
    <%= f.input :gender , :as => :radio_buttons%>
    <%= f.input :school %>
    <%= f.input :phone_1 %>
    <%= f.input :phone_2 %>
    </div>
    <div class="col-md-6">
    <%= f.input :date_of_birth ,as: :date_picker, :label => 'Date Of Birth',
                  input_html: {data: {date_options: {defaultDate: '01/01/1997'}}}  %>
    <%= f.label :address %>
    <%= f.input :line_1 %>
    <%= f.input :line_2 %>
    <%= f.input :city %>
    <%= f.input :country, as: :country, priority: ["India"] %>
    <%= f.button :submit %>
    </div>
  </div>
<% end %>

app/views/students/edit.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Student %></h1>
</div>
<%= render :partial => 'form' %>

app/views/students/index.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => Student %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:roll_no) %></th>
      <th><%= model_class.human_attribute_name(:gender) %></th>
      <th><%= model_class.human_attribute_name(:phone_1) %></th>
      <th><%= model_class.human_attribute_name(:phone_2) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.id %></td>
        <td><%= student.name %></td>
        <td><%= student.roll_no %></td>
        <td><%= student.gender %></td>
        <td><%= student.phone_1 %></td>
        <td><%= student.phone_2 %></td>
        <td>
          <%= link_to student_path(student), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to student_path(student), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_student_path,
            :class => 'btn btn-primary' %>

app/views/students/new.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Student %></h1>
</div>
<%= render :partial => 'form' %>

app/views/students/show.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => Student %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @student.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:roll_no) %></dt>
      <dd><pre class="prettyprint"><%= @student.roll_no %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:gender) %></dt>
      <dd><pre class="prettyprint"><%= @student.gender %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:school) %></dt>
      <dd><pre class="prettyprint"><%= @student.school %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:phone_1) %></dt>
      <dd><pre class="prettyprint"><%= @student.phone_1 %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:phone_2) %></dt>
      <dd><pre class="prettyprint"><%= @student.phone_2 %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:date_of_birth) %></dt>
      <dd><pre class="prettyprint"><%= @student.date_of_birth %></pre></dd>
      <h4>Address</h4>
      <dt class="label label-default"><%= model_class.human_attribute_name(:line_1) %></dt>
      <dd><pre class="prettyprint"><%= @student.line_1 %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:line_2) %></dt>
      <dd><pre class="prettyprint"><%= @student.line_2 %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:city) %></dt>
      <dd><pre class="prettyprint"><%= @student.city %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:country) %></dt>
      <dd><pre class="prettyprint"><%= @student.country %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              students_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_student_path(@student), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              student_path(@student),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>