config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/manage', as: 'rails_admin'
  get 'landings/index'

  resources :courses

  resources :firms

  resources :students

  resources :additional_fees

  resources :standards

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/additional_fee.rb
# == Schema Information
#
# Table name: additional_fees
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  amount     :integer
#  created_at :datetime
#  updated_at :datetime
#

class AdditionalFee < ActiveRecord::Base
  has_many :additional_fee_payments

  validates_presence_of :name, on: :create, message: "can't be blank"
  validates_presence_of :amount, on: :create, message: "can't be blank"

  rails_admin do
    field :name
    field :amount
  end

  def to_s
    self.name.to_s + ": " + self.amount.to_s
  end
  def title
    to_s
  end
end

app/controllers/additional_fees_controller.rb
class AdditionalFeesController < ApplicationController
  before_action :set_additional_fee, only: [:show, :edit, :update, :destroy]

  # GET /additional_fees
  # GET /additional_fees.json
  def index
    @additional_fees = AdditionalFee.all
  end

  # GET /additional_fees/1
  # GET /additional_fees/1.json
  def show
  end

  # GET /additional_fees/new
  def new
    @additional_fee = AdditionalFee.new
  end

  # GET /additional_fees/1/edit
  def edit
  end

  # POST /additional_fees
  # POST /additional_fees.json
  def create
    @additional_fee = AdditionalFee.new(additional_fee_params)

    respond_to do |format|
      if @additional_fee.save
        format.html { redirect_to @additional_fee, notice: 'Additional fee was successfully created.' }
        format.json { render :show, status: :created, location: @additional_fee }
      else
        format.html { render :new }
        format.json { render json: @additional_fee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /additional_fees/1
  # PATCH/PUT /additional_fees/1.json
  def update
    respond_to do |format|
      if @additional_fee.update(additional_fee_params)
        format.html { redirect_to @additional_fee, notice: 'Additional fee was successfully updated.' }
        format.json { render :show, status: :ok, location: @additional_fee }
      else
        format.html { render :edit }
        format.json { render json: @additional_fee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /additional_fees/1
  # DELETE /additional_fees/1.json
  def destroy
    @additional_fee.destroy
    respond_to do |format|
      format.html { redirect_to additional_fees_url, notice: 'Additional fee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_additional_fee
      @additional_fee = AdditionalFee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def additional_fee_params
      params.require(:additional_fee).permit(:name, :amount)
    end
end

app/views/additional_fees/_form.html.erb
<%= form_for @additional_fee, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :amount, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :amount, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  additional_fees_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/additional_fees/edit.html.erb
<%- model_class = AdditionalFee -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => AdditionalFee %></h1>
</div>
<%= render :partial => 'form' %>

app/views/additional_fees/index.html.erb
<%- model_class = AdditionalFee -%>
<div class="page-header">
  <h1><%=t '.title', :default => AdditionalFee %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:amount) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @additional_fees.each do |additional_fee| %>
      <tr>
        <td><%= additional_fee.id %></td>
        <td><%= additional_fee.name %></td>
        <td><%= additional_fee.amount %></td>
        <td><%=l additional_fee.created_at, format: :long %></td>
        <td>
          <%= link_to additional_fee_path(additional_fee), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to additional_fee_path(additional_fee), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_additional_fee_path,
            :class => 'btn btn-primary' %>

app/views/additional_fees/new.html.erb
<%- model_class = AdditionalFee -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => AdditionalFee %></h1>
</div>
<%= render :partial => 'form' %>

app/views/additional_fees/show.html.erb
<%- model_class = AdditionalFee -%>
<div class="page-header">
  <h1><%=t '.title', :default => AdditionalFee %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @additional_fee.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:amount) %></dt>
      <dd><pre class="prettyprint"><%= @additional_fee.amount %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              additional_fees_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_additional_fee_path(@additional_fee), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              additional_fee_path(@additional_fee),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>